export const Project = {
  GET_PROJECT_REQUEST: 'GET_PROJECT_REQUEST',
  GET_PROJECT_SUCCESS: 'GET_PROJECT_SUCCESS',
  GET_PROJECT_FAILED: 'GET_PROJECT_FAILED',
};

export const Team = {
  GET_TEAM_REQUEST: 'GET_TEAM_REQUEST',
  GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS',
  GET_TEAM_FAILED: 'GET_TEAM_FAILED',
};

export const Partner = {
  GET_PARTNER_REQUEST: 'GET_PARTNER_REQUEST',
  GET_PARTNER_SUCCESS: 'GET_PARTNER_SUCCESS',
  GET_PARTNER_FAILED: 'GET_PARTNER_FAILED',
};

export const Media = {
  GET_MEDIA_REQUEST: 'GET_MEDIA_REQUEST',
  GET_MEDIA_SUCCESS: 'GET_MEDIA_SUCCESS',
  GET_MEDIA_FAILED: 'GET_MEDIA_FAILED',
};

export const Subscribe = {
  SUBSCRIBE_REQUEST: 'SUBSCRIBE_REQUEST',
  SUBSCRIBE_SUCCESS: 'SUBSCRIBE_SUCCESS',
  SUBSCRIBE_FAILED: 'SUBSCRIBE_FAILED',
};

export const Donation = {
  DONATION_REQUEST: 'DONATION_REQUEST',
  DONATION_SUCCESS: 'DONATION_SUCCESS',
  DONATION_FAILED: 'DONATION_FAILED',
};

export const Summit = {
  SUMMIT_REQUEST: 'SUMMIT_REQUEST',
  SUMMIT_SUCCESS: 'SUMMIT_SUCCESS',
  SUMMIT_FAILED: 'SUMMIT_FAILED',
};

export const Volunteers = {
  VOLUNTEERS_REQUEST: 'VOLUNTEERS_REQUEST',
  VOLUNTEERS_SUCCESS: 'VOLUNTEERS_SUCCESS',
  VOLUNTEERS_FAILED: 'VOLUNTEERS_FAILED',
};

export const Event = {
  EVENT_REQUEST: ' EVENT_REQUEST',
  EVENT_SUCCESS: ' EVENT_SUCCESS',
  EVENT_FAILED: ' EVENT_FAILED',
};
export const Press = {
  PRESS_REQUEST: ' PRESS_REQUEST',
  PRESS_SUCCESS: ' PRESS_SUCCESS',
  PRESS_FAILED: ' PRESS_FAILED',
};

export const Video = {
  VIDEO_REQUEST: 'VIDEO_REQUEST',
  VIDEO_SUCCESS: 'VIDEO_SUCCESS',
  VIDEO_FAILED: 'VIDEO_FAILED',
};
export const SummitEvent = {
  SUMMITEVENT_REQUEST: ' SUMMITEVENT_REQUEST',
  SUMMITEVENT_SUCCESS: ' SUMMITEVENT_SUCCESS',
  SUMMITEVENT_FAILED: ' SUMMITEVENT_FAILED',
};

export const Audience = {
  AUDIENCE_REQUEST: 'AUDIENCE_REQUEST',
  AUDIENCE_SUCCESS: 'AUDIENCE_SUCCESS',
  AUDIENCE_FAILED: 'AUDIENCE_FAILED',
};

export const GetInvolued = {
  GET_INVOLVE_REQUEST: 'GET_INVOLVE_REQUEST',
  GET_INVOLVE_SUCCESS: 'GET_INVOLVE_SUCCESS',
  GET_INVOLVE_FAILED: 'GET_INVOLVE_FAILED',
};

export const Partnership = {
  PARTNERSHIP_REQUEST: 'PARTNERSHIP_REQUEST',
  PARTNERSHIP_SUCCESS: 'PARTNERSHIP_SUCCESS',
  PARTNERSHIP_FAILED: 'PARTNERSHIP_FAILED',
};

export const Consultation = {
  CONSULTATION_REQUEST: 'CONSULTATION_REQUEST',
  CONSULTATION_SUCCESS: 'CONSULTATION_SUCCESS',
  CONSULTATION_FAILED: 'CONSULTATION_FAILED',
};

export const Organize = {
  ORGANIZE_REQUEST: 'ORGANIZE_REQUEST',
  ORGANIZE_SUCCESS: 'ORGANIZE_SUCCESS',
  ORGANIZE_FAILED: 'ORGANIZE_FAILED',
};

export const Hero = {
  HERO_REQUEST: 'HERO_REQUEST',
  HERO_SUCCESS: 'HERO_SUCCESS',
  HERO_FAILED: 'HERO_FAILED',
};

export const Countries = {
  COUNTRIES_REQUEST: 'COUNTRIES_REQUEST',
  COUNTRIES_SUCCESS: 'COUNTRIES_SUCCESS',
  COUNTRIES_FAILED: 'COUNTRIES_FAILED',
};

export const Categories = {
  CATEGORIES_REQUEST: 'CATEGORIES_REQUEST',
  CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
  CATEGORIES_FAILED: 'CATEGORIES_FAILED',
};
